### ISSUE TITLE
how to show timeline data

### ISSUE THREAD

**Issue by LinJM** [wjaskowski/tensorflow-vs-theano-benchmark#1]
I get a timeline txt, but how can I show it ?

**Comment by wjaskowski** [comment]
The code with "timeline" is dead, so unless you modified something, you
should not get any timeline file. But if you still ask, you need to use
https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/timeline-tool


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski

**Comment by LinJM** [comment]
@wjaskowski  Thank you so much.
